# Generated by Django 5.2.14 on 2026-06-11 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0002_pokemoncache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_cherche_id', models.IntegerField()),
                ('cherche_shiny', models.BooleanField(blank=True, null=True)),
                ('cherche_nature', models.CharField(blank=True, max_length=20, null=True)),
                ('cherche_ivs_min', models.JSONField(blank=True, null=True)),
                ('cherche_talent', models.CharField(blank=True, max_length=10, null=True)),
                ('cherche_genre', models.CharField(blank=True, max_length=10, null=True)),
                ('cherche_commentaire', models.TextField(blank=True, null=True)),
                ('propositions', models.JSONField()),
                ('methode_echange', models.CharField(choices=[('link_code', 'Link Code'), ('code_ami', 'Code Ami Switch'), ('les_deux', 'Les deux')], max_length=15)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_attente', 'En attente'), ('terminee', 'Terminée'), ('expiree', 'Expirée')], default='ouverte', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='pokedex.jeu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
