# Generated by Django 5.2.14 on 2026-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='cherche_talents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
