# Generated by Django 5.2.14 on 2026-06-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_annonce_cherche_talents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='cherche_genre',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
