# Generated by Django 5.2.14 on 2026-06-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_annonce_cherche_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode_utilisee', models.CharField(choices=[('link_code', 'Link Code'), ('code_ami', 'Code Ami Switch')], max_length=15)),
                ('link_code', models.CharField(blank=True, max_length=9, null=True)),
                ('link_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='marketplace.annonce')),
                ('user_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges_demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
