# Generated by Django 5.2.14 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_echange'),
    ]

    operations = [
        migrations.AddField(
            model_name='echange',
            name='confirme_annonceur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echange',
            name='confirme_demandeur',
            field=models.BooleanField(default=False),
        ),
    ]
