# Generated by Django 5.2.14 on 2026-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_echange_confirme_annonceur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echange',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=15),
        ),
    ]
