# Generated by Django 5.2.14 on 2026-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_couleur',
            field=models.CharField(default='#7030a0', max_length=7),
        ),
    ]
