# Generated by Django 5.2.14 on 2026-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_couleur'),
        ('pokedex', '0003_pokemoncache_talents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jeux_possedes',
            field=models.ManyToManyField(blank=True, to='pokedex.jeu'),
        ),
    ]
