# Generated by Django 5.2.14 on 2026-06-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('plateforme', models.CharField(max_length=20)),
                ('echanges_online', models.BooleanField(default=True)),
                ('pokedex_regional', models.JSONField(default=list)),
                ('exclusivites', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type_vue', models.CharField(choices=[('regional', 'Régional'), ('national', 'National')], default='regional', max_length=10)),
                ('mode_shiny', models.BooleanField(default=False)),
                ('pokemon_statuses', models.JSONField(default=dict)),
                ('shiny_statuses', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.jeu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
