# Generated by Django 5.2.14 on 2026-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('nom_fr', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(max_length=300)),
                ('types', models.JSONField(default=list)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
