# Generated by Django 5.2.14 on 2026-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemoncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncache',
            name='talents',
            field=models.JSONField(default=list),
        ),
    ]
